In [1]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import (confusion_matrix,classification_report,accuracy_score)

In [2]:
dataset = load_iris()

X_train, X_test, y_train, y_test = train_test_split(dataset["data"],dataset["target"], random_state=0)

In [3]:
kn = KNeighborsClassifier(n_neighbors=3)
kn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [4]:
prediction = kn.predict(X_test)
print(confusion_matrix(y_test, prediction))
print(classification_report(y_test,prediction))
print(accuracy_score(y_test,prediction))
print(1-accuracy_score(y_test,prediction))

[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       1.00      0.94      0.97        16
           2       0.90      1.00      0.95         9

    accuracy                           0.97        38
   macro avg       0.97      0.98      0.97        38
weighted avg       0.98      0.97      0.97        38

0.9736842105263158
0.02631578947368418
